version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Для получения информации о запущенных контейнерах
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # Здесь будут храниться сертификаты, генерируемые Let's Encrypt
      - certbot_certs:/etc/nginx/certs:ro
      # Дополнительные конфиги для виртуальных хостов (папку можно создать пустой)
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      # Статические HTML-страницы (например, для ошибок)
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app_net

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx/html:/usr/share/nginx/html:rw
    depends_on:
      - nginx-proxy
    networks:
      - app_net

  web:
    build: .
    container_name: django_app
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 blogicum_project.blogicum.wsgi:application
    env_file:
      - .env
    environment:
      # Указываем домены, по которым будет доступно приложение,
      # и для которых будет запрошен сертификат
      - VIRTUAL_HOST=kvartirabezvznosa.ru,www.kvartirabezvznosa.ru,bezvznosa.ru,www.bezvznosa.ru,ipotekabezvznosa.ru,www.ipotekabezvznosa.ru
      - LETSENCRYPT_HOST=kvartirabezvznosa.ru,www.kvartirabezvznosa.ru,bezvznosa.ru,www.bezvznosa.ru,ipotekabezvznosa.ru,www.ipotekabezvznosa.ru
      - LETSENCRYPT_EMAIL=your_email@example.com
      - VIRTUAL_PORT=8000
    volumes:
      - .:/app
      - ./logs:/app/blogicum_project/logs
      - ./media:/app/media
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
  certbot_certs:
