# Generated by Django 3.2.16 on 2024-11-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='embed_video_url',
        ),
    ]
