name: Deploy to VPS

on:
  push:
    branches:
      - main  # Автоматический деплой при каждом пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # (Опционально: добавьте шаги тестирования или сборки)

      - name: Generate .env file and Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /home/karina/kvartirabezvznosa   # Убедитесь, что этот путь совпадает с расположением репозитория на VPS
            echo "Генерируем файл .env из секретов..."
            cat > .env <<EOF
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_HOST=db
            DATABASE_PORT=5432
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
            EMAIL_USE_SSL=${{ secrets.EMAIL_USE_SSL }}
            EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
            EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
            AWS_TENANT_ID=${{ secrets.AWS_TENANT_ID }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}
            AWS_S3_ENDPOINT_URL=${{ secrets.AWS_S3_ENDPOINT_URL }}
            AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }}
            AWS_S3_SIGNATURE_VERSION=${{ secrets.AWS_S3_SIGNATURE_VERSION }}
            AWS_S3_CUSTOM_DOMAIN=${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
            EOF

            echo ".env создан. Обновляем код и запускаем контейнеры..."
            git pull origin main
            docker-compose pull
            docker-compose up -d --build
